#!/bin/sh
set -e # all errors are fatal errors

command_absent() {
  ! command -v "$1" > /dev/null
}

if command_absent node; then
  echo 'node(1) not found'
  echo 'On macOS,      install     with   `brew install node`'
  echo 'On FreeBSD,    install     with   `pkg  install node`'
  echo 'On Enterprise Linux, install with `yum  install nodejs`'
  exit 1
fi

if command_absent npm; then
  echo 'npm(1) not found'
  echo 'On macOS,      install    with    `brew install node`'
  echo 'On FreeBSD,    install    with    `pkg  install npm`'
  echo 'On Enterprise Linux, install with `yum  install nodejs`'
  exit 1
fi


if command_absent weasyprint; then
  echo 'weasyprint(1) not found'
  echo 'On macOS,   install with `brew install weasyprint`'
  echo 'On FreeBSD, install with `pkg install py-weasyprint`'
  echo 'On Linux,   see https://doc.courtbouillon.org/weasyprint/v52.5/install.html#linux'
  exit 1
fi

npm install
