#!/bin/sh
set -e # all errors are fatal errors

command_absent() {
  ! command -v "$1" > /dev/null
}

if command_absent node; then
  echo 'node(1) not found, install with `brew install node` or similar'
  exit 1
fi

if command_absent prince; then
  echo 'prince(1) not found, install with `brew cask install prince` or similar'
  exit 1
fi

npm install
