#!/bin/sh
# deploy - commit built files to gh-pages branch and push
# Why don't I use another tool for this? Because they keep breaking, which is exhausting for something this simple.

set -e
set -x

remote_repo="git@github.com:josephholsten/www.josephholsten.com.git"
remote_branch="gh-pages"

head_abbr_commit_hash=`git log --pretty="%h" -n1`

echo 'Publishing site...'
cd build

    git init ||
			true
		git remote add origin "${remote_repo}" ||
			true
		git fetch origin

		git reset origin/"${remote_branch}"

    git add .
    printf 'Files to Commit: '
    find . |
        grep -c -v '^\./\.git'

    echo "Committing files from ${head_abbr_commit_hash} ..."
    git commit -m"Site updated to ${head_abbr_commit_hash}" > /dev/null 2>&1

    echo "Pushing... to $remote_repo master:$remote_branch"
		git push --force origin main:"${remote_branch}"

    # echo "Removing git..."
    # rm -fr .git

cd -
echo 'Done'
