#!/bin/sh
# deploy - commit built files to gh-pages branch and push
# Why don't I use another tool for this? Because they keep breaking, which is exhausting for something this simple.

set -e

remote_repo="https://github.com/josephholsten/www.josephholsten.com.git"
remote_branch="gh-pages"

echo 'Publishing site...'
cd build

    git init
    git add .
    # echo "Pushing... to $remote_repo master:$remote_branch"
    git remote add origin $remote_repo ||
            echo "Remote origin already exists"
    git fetch
    git reset origin/$remote_branch
    git diff "$@"

cd -
echo 'Done'

