#!/bin/sh
# diff - diff the built files in gh-pages branch

set -e

remote_repo="https://github.com/josephholsten/www.josephholsten.com.git"
remote_branch="gh-pages"

cd build

    git init
    git add .
    git remote add origin $remote_repo ||
            echo "Remote origin already exists"
    git fetch
    git reset origin/$remote_branch
    git diff "$@"

cd -
